title: Math & PL
name: Nick Burrell's Technical Blog
user_description: nickburrell.netlify.com
notes_url: "https://nickburrell.netlify.com"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: MPL-2.0
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nickburrell.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-toc

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: null
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge


sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /:title
    general:
      output: true
      permalink: /

toc:
  max_level: 3

include:
  - "_notes/**/*.md"
  - "privacy.md"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
